### ISSUE TITLE
A composer-wallet-redis problem

### ISSUE THREAD

**Issue by tanhuiya** [hyperledger/composer-tools#111]
I follow the guideline .

* Install composer-wallet-redis image and start the container.
* export NODE_CONFIG={"composer":{"wallet":{"type":"@ampretia/composer-wallet-redis","desc":"Uses  a local redis instance","options":{}}}}
* composer card import admin@test-network.card

I found the card still store in my local machine at path ~/.composer/card/
How can I check whether the card exist in the redis server?

**Comment by mbwhite** [comment]
Answered on SO.
