### ISSUE TITLE
Failed to download local Hyperledger Fabric runtime

### ISSUE THREAD

**Issue by nelsonthamhc** [hyperledger/composer-tools#112]
I faced an issue after running the command "./downloadFabric.sh".

The error is "failed to register layer: Error processing tar file(exit status 1): invalid argument.

I am running on windows 10, Ubuntu 16.04.3 LTS Xenial.

Any solution for this?

**Comment by davidkel** [comment]
I am guessing that you are using ubuntu downloaded from the windows store (ie using the Windows Subsystem for Linux), this environment is not supported and unlikely that docker is supported in this environment either. There is an issue https://github.com/hyperledger/composer/issues/65 which is about looking at how support for windows can be achieved, but currently Windows is not supported.
