### ISSUE TITLE
Align default card name to its related version: hlfv11 for the /scripts/hlfv11/createPeerAdminCard.sh

### ISSUE THREAD

**Issue by Phaserboo** [hyperledger/composer-tools#115]
createPeerAdminCard.sh under [/fabric-dev-servers/fabric-scripts/hlfv11/](https://github.com/hyperledger/composer-tools/blob/master/packages/fabric-dev-servers/fabric-scripts/hlfv11/createPeerAdminCard.sh) creates a card with name **hlfv1** instead of using a name aligned with its related version **hlfv11**.

Some of the command line reported on the version website should then updated in order to reflect the change and maintain consistency.

**Comment by davidkel** [comment]
see https://github.com/hyperledger/composer/issues/3801
closing as this is a duplicate
