### ISSUE TITLE
composer network start error

### ISSUE THREAD

**Issue by CHUQIUSHI** [hyperledger/composer-tools#127]
when i am following the tutorial
_https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial_

on the  Step Four: Deploying the business network
when i excute：

composer network start --networkName tutorial-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card

Error: Error trying to start business network. Error: Error: 2 UNKNOWN: access denied: channel [composerchannel] creator org [Org1MSP]
Command failed

**Comment by rameshnagaraju** [comment]
I too get the same Error.

**Comment by kavitha-sant** [comment]
Here is how I solved it - with help from the comment by @flibustier on [#3735](https://github.com/hyperledger/composer/issues/3735) and @knagaev on [#65](https://github.com/hyperledger/composer/issues/65) :

I inserted this one line in fabric-tools\hlfv11\startFabric.sh

`export MSYS_NO_PATHCONV=1`

before

```
# Create the channel
docker exec peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c composerchannel -f /etc/hyperledger/configtx/composer-channel.tx
```


After this run 
   .\stopFabric.sh 
   .\startFabric.sh.
Then 'composer network install' and 'composer network start' from the tutorial steps should run correctly.

**Comment by davidkel** [comment]
closing as this implies trying to run in a windows environment which is not supported.

**Comment by prathameshdamji** [comment]
Error: Error trying to start business network. Error: Unable to initalize channel. Attempted to contact 1 Peers. Last error was Error: Error: 2 UNKNOWN: Failed to deserialize creator identity, err MSP Org1MSP is unknown

**Comment by abadraja** [comment]
Same issue here on an Ubuntu machine

**Comment by zaburo** [comment]
check the instance, and delete all
docker rm $(docker ps -aq)
    docker rmi $(docker images dev-* -q)

**Comment by Gyon-Ki** [comment]
> `export MSYS_NO_PATHCONV=1`

what does this line mean?
