### ISSUE TITLE
Can't generate PeerAdmin@hlfv11

### ISSUE THREAD

**Issue by Grendel61** [hyperledger/composer-tools#129]
I've gone through the tutorials a few times. 

- I'm updated to the latest V0.19.1 of the CLI.  Did your NPX suggestion.
- Runtime is 0.19.1
- I did the export `FABRIC_VERSION=hlfv11. `
- When I start the fabric I get `FABRIC_VERSION is set to 'hlfv11'`
- I deleted the `.composer` directory. 
- Downloaded the latest tools

However, each time I run ./createPeerAdminCard.sh it creates a PeerAdmin@hlfv1 card. I was expecting it would create an PeerAdmin@hlfv11, but it doesn't. I'm worried this impacting my fabric? Causing some problems I'm having with the Composer-Playground-API port sporadically? 

Your help is appreciated.

**Comment by Grendel61** [comment]
Thanks, much appreciated

**Comment by davidkel** [comment]
closing as resolved.
