### ISSUE TITLE
Hyperledger Composer - Failed to load logger module ./winstonInjector.js: Cannot find module "."

### ISSUE THREAD

**Issue by Grendel61** [hyperledger/composer-tools#131]
I'm running HyperLedger Composer Playground

My Current Environment - 

```
├── composer-cli@0.19.1
├── composer-playground@0.19.1
├── composer-rest-server@0.19.1
├── generator-hyperledger-composer@0.19.1
├── npm@5.6.0
├── wscat@2.1.1
└── yo@2.0.2
```

I'm seeing this error in my console:
 
`Failed to load logger module ./winstonInjector.js: Cannot find module "."` 

Obviously the console.log isn't working, but otherwise I'm operating fine. The wistonInjector.js file seems to be in place in my fabric-tools directory. I reinstalled the fabric-tools directory, and restarted the playground. No change. 

Thanks in advance for your help.

**Comment by futurama92** [comment]
Same problem

**Comment by gabcamilo** [comment]
same

**Comment by davidkel** [comment]
This isn't an issue with the composer tools packages. If it is still a problem please raise an issue on 
https://github.com/hyperledger/composer repository with details of what the symptoms are.
