### ISSUE TITLE
Invalid `configtx.yaml` file.

### ISSUE THREAD

**Issue by hickscorp** [hyperledger/composer-tools#159]
Some YML parssers will trip on the fact that the `Profiles` section is declared first while referring to references of sections declared afterward (On my Linux box, it fails as it doesn't know `*OrdererDefaults` and `*ApplicationDefaults`).

The file should be changed to allow such parsers (Eg move the `Profiles` sections all the way to the end of the file.

**Comment by davidkel** [comment]
closing as not valid. The fabric-dev-servers package is not meant as an instruction for building you own fabric networks or extending or modifying the provided one. It's there purely as a simple dev server for composer users to get started.
