### ISSUE TITLE
Error using composer-wallet-ibmcos + Composer-rest-server in the cloud

### ISSUE THREAD

**Issue by akrav79** [hyperledger/composer-tools#164]
Using composer-wallet-ibmcos I successfully store cards in the Cloud.

Then I have uploaded Composer-Rest-Server as Cloud-app and have  launched 
" ~$ cf set-env {My_APP} NODE-ENV"
This works great  too.

But when app start it’s try to find admin card on path “./composer/cards/client-data”.
It seems that Rest-Server container that I pushed into the Cloud have some presets
and do not understand "type":"composer-wallet-ibmcos"

Where can I find good container?

**Comment by davidkel** [comment]
composer 0.19.17 and 0.20.2 added the various cloud wallets to the composer-rest-server docker image, but I would suggest using the latest available docker images of composer-rest-server.

**Comment by akrav79** [comment]
I've tried composer 0.20.2 with NODE-CONFIG, but I got the same error.
The same NODE-CONFIG works well with local Composer + Cloudat.
An error "lib/cardstore/walletbackedcardstore.js:74:27" in Cloud logs. 
May be I am wrong, but it seems that composer 0.20.2 do not understand what is "composer-wallet-ibmcos".
