### ISSUE TITLE
Error: Error trying to start business network. Error: Failed to connect to any peer event hubs

### ISSUE THREAD

**Issue by eladelrom** [hyperledger/composer-tools#165]
My enviourment:
Composer version: v0.20.6
MacOS 10.14.2
Node v8.15.0
npm v6.4.1

 I followed: Step 1: Getting Hyperledger Fabric running and Starting Hyperledger Fabric as per commands and had Hyperledger Fabric and creation of PeerAdminCard went well. 

I was also able to install a .bna file with no errors;
> composer network install -a some-network.bna -c PeerAdmin@hlfv1

✔ Installing business network. This may take a minute...
Successfully installed business network some-network, version 0.0.2-deploy.3
Command succeeded

When I try to start the network utilizing the network 

> composer network start --networkName some-network --networkVersion 0.0.2-deploy.3 -A admin -S adminpw -c PeerAdmin@hlfv1 --file networkadmin.card

I am getting the following errors:

Starting business network hello-network at version 0.0.2-deploy.3

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Failed to connect to any peer event hubs. It is required that at least 1 event hub has been connected to receive the commit event
Command failed

Please advice.

**Comment by carlosepp** [comment]
having the exact same issue, any news?

**Comment by usamayousuf13** [comment]
I am having the same issue while i am trying to Deploying a Hyperledger Composer blockchain business network to Hyperledger Fabric (multiple organizations).
Identities are created successfully but failed to start network

$ composer network start -c PeerAdmin@byfn-network-org1 -n systems-network -V 0.0.9 -o endorsementPolicyFile=/tmp/composer/endorsement-policy.json -A alice -C alice/admin-pub.pem -A bob -C bob/admin-pub.pem

Starting business network systems-network at version 0.0.9

Processing these Network Admins: 
	userName: alice
	userName: bob

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: Failed to connect to any peer event hubs. It is required that at least 1 event hub has been connected to receive the commit event
Command failed
