### ISSUE TITLE
Start Fabric problem

### ISSUE THREAD

**Issue by Stewthebosshog** [hyperledger/composer-tools#167]
**$ ./startFabric.sh**
Development only script for Hyperledger Fabric control
Running 'startFabric.sh'
FABRIC_VERSION is set to 'hlfv12'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
### Problem:

> IOError: [Errno 2] No such file or directory:  _'/cygdrive/c/Users/fabric-tools/fabric-scripts/hlfv12/composer/docker-compose.yml'_

I don't understand why it's doing this. Is there something that isn't configured right?

**Comment by madhivanan08** [comment]
facing below error while starting fabric

 
./startFabric.sh
Development only script for Hyperledger Fabric control
Running 'startFabric.sh'
FABRIC_VERSION is set to 'hlfv12'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)
SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)
anyone please advice
Thanks in advance
