### ISSUE TITLE
Events error with Hyperledger Composer 0.9.1 and Hyperledger Fabric rc1

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer-tools#40]
Using hyperledger composer v0.9.1 and and hyperledger rc1, I get everything to work except for listening to event. I can successfully submit trans, create/query assets and participants. I see an error "The event hub has not been connected to the event source". I can see my event successfully emitted in the Docker Logs for the chaincode peer.

**Comment by DennisM330** [comment]
Found I had to restart Node Red after defining a flow with Hyperledger Compose In node and then the error disappears and I receive the event in the Debug tab. Re-deploying the flow does not seem to help. Not sure if this is an issue or no.

**Comment by davidkel** [comment]
If this is still and issue with the latest available code could you please open a new issue with more details.

**Comment by sadonsergey** [comment]
(node:10933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The event hub has not been connected to the event source
(node:10933) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Error trying invoke business network. Error: The event hub has not been connected to the event source


Composer version: v0.16.2

**Comment by krabradosty** [comment]
@sadonsergey I've got the same error

**Comment by sivachaitanya** [comment]
did anyone resolved this ?
