### ISSUE TITLE
Add query support

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer-tools#41]
Now that we have queries in hyperledger composer, it would be nice to add the ability to execute a query as well.
--

**Comment by davidkel** [comment]
@DennisM330 could you be more explicit about what you mean here ? I am guessing you are referring to node-red integration but as composer-tools hosts more than just node-red tools I would be good if you could provide more details

**Comment by DennisM330** [comment]
Node Red integration node to support queries
