### ISSUE TITLE
Node-Red Test with New Identity Card support

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer-tools#74]
Trying to test with hyperledger composer 0.15 with the new Identity Card support in 0.15. I have been unsuccessful with authorization errors in Node-Red. Does Node-Red only supported the deprecated Composer Connection Profiles at the moment? I did run the script in fabric-tools to create a connection profile, but it seems the node-red-contrib-composer nodes cannot connect to the business network.

**Comment by ypeckstadt** [comment]
I am running into the same problem.  In my case it keeps giving the  following error.

`Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)`

This while the user has been registered for sure as everything else is working perfectly.

**Comment by DennisM330** [comment]
I found you also need to do the following prior to starting Node-Red: composer card export --file networkadmin.card --name admin@yourbusinesswork. So I got further even though it is not used the new cards. Looks like the client is still 0.14.3 though and not 0.15.0  so I will wait until the nodes are updated. "Composer runtime (0.15.0) is not compatible with client (0.14.3)"

**Comment by caroline-church** [comment]
closing as the node red nodes have now been updated. If you are still having issues please feel free to reopen
