### ISSUE TITLE
[node-red-contrib-composer] Add Get All /Resolve All feature as part of Retrieve action

### ISSUE THREAD

**Issue by mwittig** [hyperledger/composer-tools#76]
Using the "retrieve" action only allows for retrieving a single object instance of a given class and id. However, it would be nice to be able to retrieve _all instances of a given class_, as it is not (yet) possible to perform queries as part of the plugin. The client registry, i.e. the asset and participant registries, provide a method `getAll` and `resolveAll` to facilitate this.  

If you consider my feature request, I am happy to contribute on this. Please see my initial implementation which does a getAll / resolveAll if the "id"  is left empty as part of the node configuration.
https://github.com/hyperledger/composer-tools/compare/1b3e15f...mwittig:master

Please let me know what you think.

**Comment by caroline-church** [comment]
@mwittig yes we would love you to contribute.  The asset part looks really good, but the participant part you can also do a `getAll()` on a `participantRegistry`.

**Comment by mwittig** [comment]
@caroline-church thanks for the swift reply! I'll improve the participant part and issue a pull request later this week.

**Comment by mwittig** [comment]
I am closing this as to my knowledge the suggested feature has been released
