### ISSUE TITLE
Add Contribution Guidelines / Clarify need for DCO sign-off

### ISSUE THREAD

**Issue by mwittig** [hyperledger/composer-tools#80]
As there is an automatic check for DCO sign-off in commit messages as part of an pull request there should be note on contribution guidelines for this. As far as I can see, a reference to the guidelines contained in the main [composer project](https://github.com/hyperledger/composer/blob/master/CONTRIBUTING.md) should be good enough. However, what puzzles me is, that these guidelines do not contain the requirement for a "DCO sign-off". Maybe I have overlooked something?! Please advise.

**Comment by davidkel** [comment]
Should now be in the contrib guide on the main composer project in the master branch.
