### ISSUE TITLE
Error: creating resource error Card not found

### ISSUE THREAD

**Issue by Karl-Keller** [hyperledger/composer-tools#90]
Using node-red (local) version 0.17.5 with playground composer (local) version 0.2.0.  After adding node-red-contrib composer version 0.0.1 via the palette, I added a composer node with 'composer card' = test@my-hello-world.  Added an injector node and at execution node-red threw the "card not found" error.  Inspecting the ~/.composer/cards directory  showed no business net files (?).  After reading doc's, created the connection.json and metadata.json files and zipped them into a test@my-hello-world.zip.  Still getting the error above.  Where is node-red looking for card files?

**Comment by davidkel** [comment]
you create card files using the `composer card create` command, or you may have already been provided a card file from somewhere else (eg composer network start). Composer will look for cards in the card store, it doesn't look for card files themselves. You need to import a card file into the card store using `composer card import`

**Comment by richbl** [comment]
@davidkel, I appear to be running into a similar issue.

I'm running Composer Playground v0.17.4 (Fabric 1.1.0-alpha) with the node-red-contrib-composer 0.0.10, and I'm getting the same "Error: creating resource error Card not found: testUser@test-network" error. I can confirm that the card exists (`composer card list` or directly via the Composer Playground interface).

What's the best way to debug this? Do you have a test script that you run against releases that I might use for troubleshooting this issue?

BTW, not that this should be a factor, but I'm running Composer Playground on a non-default port (8081).

Thanks
